### Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b= np.array([[9.0,7.0,8.0],[6.0,5.0,8.0]])
b

array([[9., 7., 8.],
       [6., 5., 8.]])

In [5]:
# Get dimesnion Since it is one dimenstional
a.ndim

1

In [6]:
#Get Shape
b.shape

(2, 3)

In [7]:
a.shape

(3,)

In [8]:
# Get data type
a.dtype

dtype('int32')

In [9]:
# Get total size in bytes
a.nbytes

12

In [12]:
#Inorder to reduce size take the dtype integer from int32 - int16
c = np.array([1,2,3,],dtype='int16')
c

array([1, 2, 3], dtype=int16)

In [13]:
c.nbytes

6

In [14]:
a.itemsize

4

### Changing specific elements and columns

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [19]:
# Get a specefic column and row [r,c] row and column statrts with 0
a[1,5]

13

In [20]:
#Also
a[1,-2]

13

In [21]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
a[:,2]

array([ 3, 10])

In [23]:
# Getting a little more fancy [start index:end index: step size] w.r.t column where indexing [0 - (n-1)]
a[0,1:6:2]


array([2, 4, 6])

In [24]:
# Change a particular element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
# Changing a whole column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [29]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
# Getting a specefic elemnt- o row , 2nd column , 2nd element
b[0,1,1]

4

In [31]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
b[:,1,0]

array([3, 7])

In [34]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different types of array

In [36]:
#Creating zero matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# 2 times 3*3 matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
# 2 times triplet(3) of 3*2 matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [43]:
# All ones matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Any other number (full_like)
np.full(a.shape,4)
#
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [48]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.78423428, 0.80560178, 0.82992593],
        [0.29063537, 0.0499685 , 0.79725345]],

       [[0.20863938, 0.24234993, 0.75540033],
        [0.62271016, 0.91655987, 0.61093267]],

       [[0.00283913, 0.37149263, 0.65565842],
        [0.59536482, 0.47080835, 0.34319251]],

       [[0.92896203, 0.43842453, 0.6155124 ],
        [0.72957102, 0.69240436, 0.84780067]]])

In [49]:
np.random.random_sample(a.shape)

array([[0.20789286, 0.68681101, 0.74133556, 0.21641946, 0.21036854,
        0.3979347 , 0.34729702],
       [0.47047306, 0.25947676, 0.95298211, 0.88003806, 0.85804983,
        0.86968307, 0.00287954]])

In [54]:
# Random integer values - 7 - [values less than 7 ]
np.random.randint(7, size=(3,3))

array([[0, 6, 5],
       [0, 3, 2],
       [2, 1, 6]])

In [55]:
# Values between 4-7
np.random.randint(4,7, size=(3,3))

array([[4, 4, 6],
       [4, 5, 4],
       [5, 5, 6]])

In [56]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
# multiplying the number of arrays
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [60]:
# RIGHT MUTLIPICATION
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
# AXIS=1
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [67]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
# Careful while copying not b=a 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [71]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [72]:
a + 2

array([3, 4, 5, 6])

In [73]:
a - 2

array([-1,  0,  1,  2])

In [74]:
a * 3

array([ 3,  6,  9, 12])

In [75]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [76]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [77]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [78]:
# Sin Value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [79]:
# Cos Value
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [82]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# multiplying not directly a*b but with a matrix multipliier
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [83]:
 # Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
##https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# Go Here for Eigen values
# Inverse of a Matrix


In [84]:
# Statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# Finding min
np.min(stats)

1

In [86]:
# Finding Max
np.max(stats)

6

In [87]:
np.max(stats,axis=0)

array([4, 5, 6])

In [88]:
np.max(stats,axis=1)

array([3, 6])

In [89]:
# Sum of all Values
np.sum(stats)

21

In [90]:
# axis = 0 means rows ( goes vaertically)
np.sum(stats, axis =0)

array([5, 7, 9])

In [91]:
# axis =1 means column ( goes horizontally)
np.sum(stats, axis =1)

array([ 6, 15])

### Re-organizing arrays

In [93]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [95]:
# Vertically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [100]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
h2

array([[0., 0.],
       [0., 0.]])

In [102]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [103]:
pwd

'C:\\Users\\HP'

In [105]:
cd /Users/HP/Desktop/Data Science/Project

C:\Users\HP\Desktop\Data Science\Project


In [107]:
filedata = np.genfromtxt('numpy keith.txt',delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [110]:
# Converting Float type (Real) into (integer type 32)
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean masking and Advanced Indexing

In [111]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [112]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [113]:
#Just taking care of the first horizontal row
np.all(filedata > 50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [116]:
np.any(filedata > 50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [118]:
np.all(filedata > 50 , axis=1)

array([False, False, False])

In [119]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [120]:
# Reversing our condition by ~ that is <50 and > 100
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])